name: recipe_finder

packages:
  - modules/*
  - modules/**/*

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  get:
    exec: fvm flutter pub get
  gen:
    description: Build all generated files for Flutter packages in this project.
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    select-package:
      depends-on: build_runner
  clean:pubspec.lock:
    run: rm pubspec.lock
  test:
    exec: fvm flutter test