// Mocks generated by Mockito 5.4.2 from annotations
// in domain/test/lib/data_sources/local/local_recipe_favorite_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/data_sources/local/local_recipe_favorite_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalRecipeFavoriteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRecipeFavoriteDataSource extends _i1.Mock
    implements _i2.LocalRecipeFavoriteDataSource {
  MockLocalRecipeFavoriteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveRecipe(Map<String, dynamic>? recipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [recipe],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<List<Map<String, dynamic>>> getFavoriteRecipes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteRecipes,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<void> removeRecipe(String? recipeId) => (super.noSuchMethod(
        Invocation.method(
          #removeRecipe,
          [recipeId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
